#!/bin/bash

# ask for the video file to decode (complete path)
echo processing video data from a vehicle log, please specify the path to the log video 
read video_path  

# ask for the target parameters to decode 
echo please specify the target parameters in quotes, separated by commas 
read target_params 

# next we will invoke ffmpeg, saving the images to a new file in the working directory 
# this is where we are going to save it, with the output files nammed as "sample-%08d.png" 
images_path="$PWD" 
images_path+="/output_images/sample-%08d.png"

# need to make/clear the output images directory 
mkdir output_images

ffmpeg -i $video_path $images_path 

# run the data through the python script 
python recognize_data.py --directory output_images --targets target_params

